"""Data models used in the project."""

from pydantic import BaseModel, ValidationError


class Example(BaseModel):
    """A dataset sample from an instruction-following dataset."""

    key: int
    prompt: str
    instruction_id_list: list[str]
    kwargs: list[dict[str, str | int | float | bool | list[str] | None]]


class Kwarg(BaseModel):
    """A keyword argument for an instruction function."""

    name: str
    value: str | int | float | bool | list[str]


class GeneratedExample(BaseModel):
    """A dataset sample generated by a model."""

    new_prompt: str
    new_instruction_id_list: list[str]
    new_kwargs: list[list[Kwarg]]

    def model_post_init(self, __context: None) -> None:
        """Validation after the model is initialized.

        Raises:
            ValidationError:
                If the number of instruction IDs does not match the number of keyword
                argument lists.
        """
        if len(self.new_instruction_id_list) != len(self.new_kwargs):
            raise ValidationError(
                "The number of instruction IDs must match the number of keyword "
                f"argument lists. Got {len(self.new_instruction_id_list)} "
                f"instruction IDs and {len(self.new_kwargs)} keyword argument lists."
            )

        self.new_kwargs = [
            [kwarg for kwarg in kwarg_list if kwarg.value]
            for kwarg_list in self.new_kwargs
        ]
